import { createSlice } from '@reduxjs/toolkit'

//inital state
const initialState = {
  modalShown: false,
  loginFormShown: false,
  userLoggedIn: true,
  currentUser: null,
  chosenPhoto: {
    pictureUrl: '',
    pictureTitle: '',
    pictureExplanation: '',
    pictureCopyright: '',
  },
}

const appSlice = createSlice({
  name: 'app',
  initialState,
  reducers: {
    changeModalVisible: (state) => {
      state.modalShown = !state.modalShown
    },
    changeUserLoggedIn: (state) => {
      state.userLoggedIn = !state.userLoggedIn
    },
    setActiveUser: (state, actions) => {
      state.currentUser = actions.payload
    },
    showLoginForm: (state) => {
      state.loginFormShown = true
    },
    hideLoginForm: (state) => {
      state.loginFormShown = false
    },
  },
})

//exporting actions
export const { changeModalVisible, changeUserLoggedIn, showLoginForm, hideLoginForm, setActiveUser } = appSlice.actions

//export reducer generated by createSlice
export default appSlice.reducer
