import { createSlice } from '@reduxjs/toolkit'

//inital state
const initialState = {
  modalShown: false,
  sideMenuShown: false,
  loginFormShown: false,
  userLoggedIn: false,
  currentUser: null,
  chosenPhotoShown: false,
  chosenPhoto: {
    url: '',
    title: 'Template title',
    explanation: 'Template paragraph',
    copyright: 'tempalte author',
  },
}

const appSlice = createSlice({
  name: 'app',
  initialState,
  reducers: {
    changeModalVisible: (state) => {
      state.modalShown = !state.modalShown
    },
    changeSideMenuVisible: (state) => {
      state.sideMenuShown = !state.sideMenuShown
    },
    changeUserLoggedIn: (state) => {
      state.userLoggedIn = !state.userLoggedIn
    },
    setUserIn: (state) => {
      state.userLoggedIn = true
    },
    setUserOut: (state) => {
      state.userLoggedIn = false
    },
    setActiveUser: (state, actions) => {
      state.currentUser = actions.payload
    },
    showLoginForm: (state) => {
      state.loginFormShown = true
    },
    hideLoginForm: (state) => {
      state.loginFormShown = false
    },
    hideChosenPhoto: (state) => {
      state.chosenPhotoShown = false
    },
    showChosenPhoto: (state) => {
      state.chosenPhotoShown = true
    },
    setChosenPhoto: (state, actions) => {
      // state.chosenPhoto.pictureCopyright = actions.payload.pictureCopyright
      state.chosenPhoto.explanation = actions.payload.explanation
      state.chosenPhoto.title = actions.payload.title
      state.chosenPhoto.url = actions.payload.url
    },
  },
})

//exporting actions
export const {
  changeModalVisible,
  changeUserLoggedIn,
  setUserIn,
  setUserOut,
  showLoginForm,
  hideLoginForm,
  setActiveUser,
  setChosenPhoto,
  hideChosenPhoto,
  showChosenPhoto,
  changeSideMenuVisible,
} = appSlice.actions

//export reducer generated by createSlice
export default appSlice.reducer
